name: Testing Automation Anypoint

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install Anypoint CLI
        run: npm install -g anypoint-cli-v4

      # Automation using Any CLI
      - name: Automation using Any CLI
        run: anypoint-cli-v4 account:user:describe -o json --environment dev  --client_id cf35d4be7ac7441ab443e09eced6fca6 --client_secret 5264E7A842BD47Ceaa57e6e6Dd12E311

     # Automation using Any CLI
      - name: List cloudhub 1 applications
        run: anypoint-cli-v4 runtime-mgr:cloudhub-application:list -o json --environment dev --client_id cf35d4be7ac7441ab443e09eced6fca6 --client_secret 5264E7A842BD47Ceaa57e6e6Dd12E311

